-- MySQL Script generated by MySQL Workbench
-- Tue Sep  5 18:38:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cliente_produto
-- -----------------------------------------------------
-- Registro da relação cliente/ produto.

-- -----------------------------------------------------
-- Schema cliente_produto
--
-- Registro da relação cliente/ produto.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cliente_produto` ;
USE `cliente_produto` ;

-- -----------------------------------------------------
-- Table `cliente_produto`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente_produto`.`cliente` (
  `IDcliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente_produto`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente_produto`.`produto` (
  `IDproduto` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `cliente_IDcliente` INT NOT NULL,
  PRIMARY KEY (`IDproduto`),
  INDEX `fk_produto_cliente_idx` (`cliente_IDcliente` ASC) VISIBLE,
  CONSTRAINT `fk_produto_cliente`
    FOREIGN KEY (`cliente_IDcliente`)
    REFERENCES `cliente_produto`.`cliente` (`IDcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
